version: "2"
services:
  test-db:
    image: postgres:9.5
    ports:
      - "5432"
    env_file:
      - test.env
    volumes:
      - "test-db-data:/var/lib/postgresql/data"
volumes:
  test-db-data:
