#!/bin/bash
set -e -o pipefail

SCRIPTDIR=$(cd -P $(dirname $0); pwd)
DOCKERFILE=${SCRIPTDIR}/docker-compose-dev.yml
if ! docker-compose -f $DOCKERFILE ps | egrep -q db.*Up; then
  docker-compose -f $DOCKERFILE up -d
  echo "Sleeping 4 secs to give DB time to start..."
  sleep 4
fi

DBPORT=$(docker inspect -f '{{index .NetworkSettings.Ports "5432/tcp" 0 "HostPort"}}' backend_dev-db_1)
DBHOST=$(docker-machine ip $(docker-machine active))

source $SCRIPTDIR/development.env
export DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DBHOST}:${DBPORT}/${POSTGRES_USER}

# if we're gonna run psql, splice in the db conninfo argument:
if [[ $1 == "psql" ]]; then
  shift
  set -- "psql" "-d" "$DATABASE_URL" "$@"
fi

exec "$@"
